# Use the official Node.js image as a base
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy the environment files
COPY config/.env.local config/.env.test ./config/


# Expose the application's port
EXPOSE 3000

# Define the environment variable for NODE_ENV
ENV NODE_ENV=local

# Define the default command to run the application
CMD ["npm", "start"]
